### ISSUE TITLE
Rows re-generated after reloading dashboard

### ISSUE THREAD

**Issue by mobitar** [ankane/field_test#10]
First let me say how absolutely wonderful this framework is. _It just works_. So beautifully simple.

I'm noticing some strange ghostly behavior: if I go in my local database and delete all the rows from `field_test_memberships`, then refresh the dashboard, the rows are automatically regenerated with the last known values.

How is it doing this, and how can I permanently clear testing data?

**Comment by mobitar** [comment]
Actually, figured out what the issue was. I had in one of my templates

```
"onclick" => "#{field_test_converted(:button_color)}"}
```

which compiled correctly, but executed immediately on page load.

**Comment by ankane** [comment]
Great, glad you solved it 👍
