### ISSUE TITLE
Exclude users from experiments

### ISSUE THREAD

**Issue by pfeiffer** [ankane/field_test#21]
Hi! In our projects we're currently rolling our own A/B tool very similar to FieldTest.
Would love to switch to FieldTest and contribute to this instead.

One feature that we use extensively and FieldTest doesn't support at the moment, is the ability to exclude certain participants from experiments based on conditions. Say you only want to run a test for users that are in a certain country, or exclude paying customers, or only for users signed up after a certain date etc. Participants not part of an experiment, would simply be served the control variant and not count in metrics.

It's obviously not feasible to define this in the YAML-format.

A suggestion could be to allow defining experiments in Ruby instead. This could also
follow Rails-style definition of experiments in eg. `app/experiments`

Example from the top of my head:

```ruby
# eg app/experiments/button_color_experiment.rb
class ButtonColorExperiment < FieldTest::Experiment
  description 'Red vs blue'
  variants :red, :blue # or variants red: 85, blue: 15 for weighted

  def enabled?
    participant.zip == '90210'
  end
end
```

I'd love to give it a go, but would appreciate your thoughts beforehand. I think it should be possible
to implement it in a way that is backwards compatible with the YAML experiment configuration.

What do you think? 🎯

**Comment by ankane** [comment]
Hey @pfeiffer, you can accomplish this now by passing `exclude: true` to `field_test` for participants that shouldn't be in the experiment. We could add a more advanced exclude method like:

```ruby
FieldTest.exclude_method = lambda do |experiment, participants, request|
  # return true for exclude
end
```

I considered the `app/experiments` approach when designing field test but ultimately went with the config file.

**Comment by pfeiffer** [comment]
Just had a look at the `field_test`-helper and what you're proposing is fairly simple to implement. Awesome!

Regarding defining experiments in `app/experiments` vs YAML, what made you decide on YAML?

In this specific use-case the method for excluding participants would feel much more 'right', if defined together with the specific experiment and not as a global proc that's used in all experiments. In many cases the shared exclude method would end up with many `if experiment == ... ` to set exclusions for specific experiments.

The current YAML-syntax also feels a bit weird eg. when defining weights, as you have to ensure that the index of the variant match the index of the weight under a different key.

```yaml
variants:
  - red
  - blue
  - orange
  - black
  - ...
weights:
  - 40
  - 10
  - 10
  - ...
```

Cheers!

**Comment by florianroesler** [comment]
Hey @ankane,
I needed to exclude mobile users from certain A/B tests and this issue and your above comment led me to a simplistic solution based on the `browser` gem:
```ruby
module FieldTestHelper
  def field_test_with_mobile_excluded(name)
    exclude = Browser.new(request.user_agent).then { |browser| browser.device.mobile? || browser.device.tablet? }

    field_test(name, exclude: exclude)
  end
end
```


I think the README could include a section about the possibility to pass in a boolean exclude parameter. Following the documentation, I assumed the exclusion was limited to bots and IPs.

If you need, I could contribute my thoughts to that section.

**Comment by ankane** [comment]
@florianroesler Good call. Added it to the readme.

@pfeiffer Sorry for the (long) delay. If I remember correctly, YAML was chosen instead of `app/experiments` to make experiment naming a little bit simpler. Since experiment names could get complex, I didn't want users to have to deal with the mapping between `field_test(:complex_name)` and the `ComplexNameExperiment` class.
