### ISSUE TITLE
Use FieldTest in Sidekiq Workers/Models

### ISSUE THREAD

**Issue by keesbriggs** [ankane/field_test#24]
I am using a Sidekiq worker to send text messages to individuals to poll them on whether they might appear for (or flake on) on a job. We want to A/B test the value of the message. I happened upon FieldTest and really like the interface, and would really like to incorporate it into our system.

Your instructions stated:

**Refer to it in controllers, views, and mailers.**
```
button_color = field_test(:button_color)
```
However, it does not seem to work in Sidekiq Workers or models. Any particular reason? Is there something I could do to get this working in a Sidekiq worker?

Also, how might I write an RSpec that tests both sides of a simple boolean variant?

**Comment by ankane** [comment]
Hey @keesbriggs, just add a section to the docs on accessing variants outside of controllers, views, and mailers: https://github.com/ankane/field_test#jobs
