### ISSUE TITLE
Old experiment data preventing conversions from being tracked in new experiments

### ISSUE THREAD

**Issue by dpaola2** [ankane/field_test#31]
We ran our first experiment for a couple of weeks using two conversion events in our funnel. It worked very well and we were all super duper happy!

We updated the old experiment and marked the winning variant. Then we proceeded with the second test. This test used the same name for the conversion events, different names for everything else. (These are the same events we push elsewhere, into analytics, data warehouse, reporting, etc).

However, this time, none of the conversion events seemed to track correctly. I tried to rename the new conversion events (suffixed with a number) and still, no dice.

What ultimately worked was deleting the original experiment from the yaml configuration file.

I would very much like to dig into the code and assist in debugging this at some point in the future, since I have really enjoyed using field_test. Wanted to submit this here in case anyone else sees this issue arise.

Thanks for a great library, @ankane !

**Comment by ankane** [comment]
Hey @dpaola2, haven't heard of that issue. It should be fine to reuse goal names across experiments (if everything is working correctly). Are there any events in the `field_test_events` table for the 2nd experiment?

**Comment by dpaola2** [comment]
I spoke too soon. The issue is that with the new iOS 14.5 update, when a user hits a website that uses field_test will be invisible to the A/B test conversion tracking events somehow when they do it via an embedded browser (such as tapping an FB or Instagram ad).

**Comment by dpaola2** [comment]
For those watching from the cheap seats: it turns out the iOS 14.5 update somehow messes with embedded browsers when using field_test in conjunction with the ahoy integration (as per the README). Switching that off resolved the issue.
