### ISSUE TITLE
Feature toggle, rollout library

### ISSUE THREAD

**Issue by cristi** [ankane/field_test#38]
hey @ankane thank you for all these fantastic gems, I've been using field_test and ahoy for a while now.
I'm sure this is not the best place to ask, but bear with me :)
through all of those 280 repos you have, did you happen to build a feature toggle and/or gradual rollout library that would complement field_test?

**Comment by ankane** [comment]
Hey @cristi, I haven't built anything for that, but have used `ledermann-rails-settings` for it (specifically [1.x versions](https://github.com/ledermann/rails-settings/tree/v1.2.1), which support both global and record-specific settings).

**Comment by cristi** [comment]
thanks for the reply, I'll give it try! Closing
