### ISSUE TITLE
Support when there is not yet a current_user/participant?

### ISSUE THREAD

**Issue by kcm** [ankane/field_test#4]
We have a use case for sending out email when we don't have a user to associate yet (think: lead gen). We also can't proactively create a user for each one, both for efficiency, and because the email might be going to someone who already has an account.

What's the best strategy, if any, for using field_test here?

**Comment by ankane** [comment]
Hey @kcm, `participant` can also be a string (instead of a model instance), so you'd likely want to use the person's email address.

**Comment by kcm** [comment]
Ah, I see that now. Nice. Thanks!
