### ISSUE TITLE
BinaryTest supports up to 4 variants

### ISSUE THREAD

**Issue by rmontgomery429** [ankane/field_test#42]
Is this just an oversight or is there a reason to support only 3 variants when `BinaryTest` appears to support 4?

https://github.com/ankane/field_test/blob/ab2d7d29d0b9f789831569f6d017ef3ab59d0517/lib/field_test/experiment.rb#L144

If you are open to changing this to support 4 variants, I'm happy to submit a Pull Request. 

Do you prefer this being: 

1) a straight magic number replacement (change `3` to `4` and add a comment explaining it) 
2) a reference to a local constant named something like `BINARY_TEST_VARIANT_MAX` or 
3) a change to add that same constant to the `BinaryTest` gem exposing its own variant max constant (`BinaryTest::VARIANT_MAX`)?

Thank you for this awesome gem and all your other awesome gems, they are awesome!

**Comment by ankane** [comment]
Hey @rmontgomery429, check out #30.
