### ISSUE TITLE
Experiment showing 0 conversions

### ISSUE THREAD

**Issue by petebytes** [ankane/field_test#43]
Experiment is showing 0 conversions, when I click on details I can see that there are participants which converted.

`experiments:
  landing_page:
    variants:
      - 0
      - 1

exclude:
  bots: true
`

FieldTest::Membership.last
=> #<FieldTest::Membership id: 27, participant_type: "User", participant_id: "2", experiment: "landing_page", variant: "0", created_at: "2022-12-18 10:24:37.263690000 +0000", converted: true>

experiment = FieldTest::Experiment.find(:landing_page)
experiment.results
=> {0=>{:participated=>0, :converted=>0, :conversion_rate=>nil, :prob_winning=>0.5}, 1=>{:participated=>0, :converted=>0, :conversion_rate=>nil, :prob_winning=>0.5}}

FieldTest::Experiment.all
=> [#<FieldTest::Experiment:0x00007f78d3527210 @id="landing_page", @name="Landing Page", @description=nil, @variants=[0, 1], @weights=[1, 1], @winner=nil, @closed=nil, @keep_variant=nil, @goals=["conversion"], @goals_defined=false, @use_events=nil>]

**Comment by petebytes** [comment]
Changed the variants to varone and vartwo and now it works.

**Comment by ankane** [comment]
Hi @petebytes, thanks for the reporting. Added a warning for non-string variants.
