### ISSUE TITLE
Any plans to use Redis to store participation?

### ISSUE THREAD

**Issue by avishai** [ankane/field_test#8]
Just curious, since the old Split and Vanity gems both use Redis as their storage backend. Are there any performance penalties from using `field_test` on a high-traffic website?

**Comment by ankane** [comment]
Hey @avishai, no plans right now. The database calls are simple and pretty fast. As always, keep an eye on the performance of your DB and adjust accordingly.

**Comment by avishai** [comment]
Thanks @ankane, sounds good.
